### ISSUE TITLE
"Ecto Best Practices" inconsistent on sidebar

### ISSUE THREAD

**Issue by pdilyard** [absinthe-graphql/website#33]
The sidebar link to "Ecto Best Practices" in the guides is only there on certain pages (which I'm guessing was not the intention).

The link is available on these pages:
http://absinthe-graphql.org/guides/context/
http://absinthe-graphql.org/guides/deprecation/
http://absinthe-graphql.org/guides/variables/
http://absinthe-graphql.org/guides/adapters/
http://absinthe-graphql.org/guides/ecto-best-practices/

But hidden on these pages:
http://absinthe-graphql.org/guides/custom-scalars/
http://absinthe-graphql.org/guides/introspection/

Weirdly, this doesn't seem to be completely consistent, as I could've sworn it was always hidden on the "Guide Index" page as well, but now it seems to be there.

**Comment by benwilson512** [comment]
Hey! I think we had a build error, we'll look into it and re-deploy :)

**Comment by pdilyard** [comment]
Sounds good.

Love the work you guys have done, looks awesome so far and I can't wait to start using it at work!

**Comment by bruce** [comment]
Seems to be fine now -- not a build error on our part, it looks like you were just too damned fast, @pdilyard, and you beat GitHub Pages's cache invalidation/CDN propagation ;-)
