### ISSUE TITLE
is Ecto Best Practices outdated?

### ISSUE THREAD

**Issue by G3z** [absinthe-graphql/website#63]
Isn't the whole point of this page outdated ?
doens't `assoc` solve the problem described ?
```
object :user do
    field :id, :id
    field :name, :string
    field :email, :string
    field :groups, list_of(:group), resolve: assoc(:groups)
  end
```

_i'm slowly moving my first steps with elixir, phoenix and absinthe so i can be terribly wrong_

**Comment by bruce** [comment]
Yes, but absinthe_ecto isn't actually in Hex yet (as of this moment at least). This will be removed/cleaned up, expanded sometime soon. PRs are always welcome too, of course.

**Comment by esistgut** [comment]
absinthe_ecto is in Hex now.

**Comment by benwilson512** [comment]
PR welcome to update :)
