### ISSUE TITLE
Footer Links?

### ISSUE THREAD

**Issue by lynnwallenstein** [absinthe-graphql/website#9]
Do we need links to licenses or any such stuff?

**Comment by bruce** [comment]
Maybe just something like:

Please report any issues & contribute changes to the [website repository](https://github.com/absinthe-graphql/website/issues). Thanks!

**Comment by bruce** [comment]
Also:

Background image ["green"](https://www.flickr.com/photos/anitacanita/4635683623) by Ana C, license available [here](https://creativecommons.org/licenses/by-nc-nd/2.0/).
